[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar-colors.conf'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.conf'
output_path = '~/.config/rofi/colors.rasi'

[templates.mako]
input_path = '~/.config/matugen/templates/mako-colors'
output_path = '~/.config/mako/config'
post_hook = 'makoctl reload'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.conf'
output_path = '~/.config/starship.toml'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/config'
post_hook = 'pkill -USR1 cava'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian-colors.css'
output_path = '~/obsidian/The Brain/.obsidian/snippets/matugen.css'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.spotify]
input_path = '~/.config/matugen/templates/spicetify-colors.ini'
output_path = '~/.config/spicetify/Themes/Sleek/color.ini'
post_hook = "sh -c 'if pgrep -x spotify >/dev/null; then spicetify watch -s 2>&1 | sed \"/Reloaded Spotify/q\"; else spicetify -n apply; fi'"

[templates.vesktop]
input_path = '~/.config/matugen/templates/discord-colors.css'
output_path = '~/.config/Vencord/themes/midnight-discord.css'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'