##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = float-satty
    match:class = ^com\.gabm\.satty$
    
    float = on
    center = on
    size = 900 700
}

windowrule {
    name = spotify-workspace
    match:class = ^(Spotify)$
    
    workspace = 5
    suppress_event = activate activatefocus
}

windowrule {
    name = float-imv
    match:class = ^(imv)$
    
    float = on
    center = on
    size = 900 600
}

windowrule {
    name = float-mpv
    match:class = ^(mpv)$
    
    float = on
    center = on
    size = 1280 720
}

layerrule {
    name = rofi-effects
    match:namespace = ^rofi$

    dim_around = on
    animation = popin
}