cursor            {{ colors.primary.dark.hex }}
cursor_text_color {{ colors.on_primary.dark.hex }}

foreground            {{ colors.on_background.dark.hex }}
background            {{ colors.background.dark.hex }}
selection_foreground  {{ colors.on_secondary.dark.hex }}
selection_background  {{ colors.secondary.dark.hex }}
url_color             {{ colors.tertiary.dark.hex }}

#: black 000000 767676
color0  {{ colors.outline.dark.hex }}
color8  {{ colors.outline.dark.hex }}
#: red cc0403 f2201f
color1  {{ colors.error.dark.hex }}
color9  {{ colors.error.dark.hex }}
#: green 19cb00 23fd00
color2  {{ colors.tertiary.dark.hex }}
color10 {{ colors.tertiary.dark.hex }}
#: yellow cecb00 fffd00
color3  {{ colors.secondary.dark.hex }}
color11 {{ colors.secondary.dark.hex }}
#: blue 0d73cc 1a8fff
color4  {{ colors.primary.dark.hex }}
color12 {{ colors.primary.dark.hex }}
#: magenta cb1ed1 fd28ff
color5  {{ colors.inverse_primary.dark.hex }}
color13 {{ colors.inverse_primary.dark.hex }}
#: cyan 0dcdcd 14ffff
color6  {{ colors.on_primary_container.dark.hex }}
color14 {{ colors.on_primary_container.dark.hex }}
#: white dddddd ffffff
color7  {{ colors.on_background.dark.hex }}
color15 {{ colors.on_background.dark.hex }}

mark1_foreground {{ colors.on_primary.dark.hex }}
mark1_background {{ colors.primary.dark.hex }}
mark2_foreground {{ colors.on_secondary.dark.hex }}
mark2_background {{ colors.secondary.dark.hex }}
mark3_foreground {{ colors.on_tertiary.dark.hex }}
mark3_background {{ colors.tertiary.dark.hex }}