palette = "matugen"

[palettes.matugen]
primary = "{{ colors.primary.dark.hex }}"
secondary = "{{ colors.secondary.dark.hex }}"
tertiary = "{{ colors.tertiary.dark.hex }}"
error = "{{ colors.error.dark.hex }}"
text = "{{ colors.on_background.dark.hex }}"

[character]
success_symbol = "[❯](tertiary)"
error_symbol = "[❯](error)"

[directory]
style = "bold primary"
read_only_style = "error"

[cmd_duration]
style = "bold primary"