# : Manager [[[

[mgr]
cwd = { fg = "#f0dfd8" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#d8ca57", bg = "#d8ca57" }
marker_cut      = { fg = "#ebe4aa", bg = "#ebe4aa" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#cfc890", bg = "#cfc890" }

# Count
count_copied   = { fg = "#1f1c00", bg = "#ebe4aa" }
count_cut      = { fg = "#1f1c00", bg = "#ebe4aa" }
count_selected = { fg = "#542202", bg = "#cfc890" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb690" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#ffb690", bold = true, bg = "#1a120e" }
inactive  = { fg = "#e6beab", bg = "#1a120e" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#ffb690", fg = "#542202", bold = true }
normal_alt  = { bg = "#52443d", fg = "#d7c2b9" }

# Select mode
select_main = { bg = "#e6beab", fg = "#432b1e", bold = true }
select_alt  = { bg = "#52443d", fg = "#d7c2b9" }

# Unset mode
unset_main = { bg = "#cfc890", fg = "#353107", bold = true }
unset_alt  = { bg = "#52443d", fg = "#d7c2b9" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#bf6439" }
perm_write = { fg = "#8a823c" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#ccbb30" }
perm_sep   = { fg = "#ff7331" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#ffb690", bg = "#413732" }
progress_error  = { fg = "#ffb4ab", bg = "#413732" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413732" }
cand = { fg = "#ffb690" }
rest = { fg = "#542202" }
desc = { fg = "#f0dfd8" }
separator = " ▶ "
separator_style = { fg = "#f0dfd8" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#cfc890" }
title_warn  = { fg = "#ffb690" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#ffb690" }
active = { fg = "#cfc890", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb690" }
value  = { fg = "#f0dfd8" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#ffb690", bg = "#542202" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#ffb690" }
title   = {}
hovered = { fg = "#ebe4aa", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#f0dfd8" }
run    = { fg = "#f0dfd8" }
footer = { fg = "#432b1e", bg = "#e6beab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#f0dfd8" },
    { url = "*/", fg = "#ffb690" },
]

# : ]]]