# : Manager [[[

[mgr]
cwd = { fg = "#f0dedd" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ffb547", bg = "#ffb547" }
marker_cut      = { fg = "#ffdead", bg = "#ffdead" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e4c18d", bg = "#e4c18d" }

# Count
count_copied   = { fg = "#281900", bg = "#ffdead" }
count_cut      = { fg = "#281900", bg = "#ffdead" }
count_selected = { fg = "#561d20", bg = "#e4c18d" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb3b2" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#ffb3b2", bold = true, bg = "#1a1111" }
inactive  = { fg = "#e6bdbc", bg = "#1a1111" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#ffb3b2", fg = "#561d20", bold = true }
normal_alt  = { bg = "#524343", fg = "#d7c1c1" }

# Select mode
select_main = { bg = "#e6bdbc", fg = "#442929", bold = true }
select_alt  = { bg = "#524343", fg = "#d7c1c1" }

# Unset mode
unset_main = { bg = "#e4c18d", fg = "#422c05", bold = true }
unset_alt  = { bg = "#524343", fg = "#d7c1c1" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#bc4f4d" }
perm_write = { fg = "#af7929" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#ffa014" }
perm_sep   = { fg = "#ff4540" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#ffb3b2", bg = "#423736" }
progress_error  = { fg = "#ffb4ab", bg = "#423736" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#423736" }
cand = { fg = "#ffb3b2" }
rest = { fg = "#561d20" }
desc = { fg = "#f0dedd" }
separator = " ▶ "
separator_style = { fg = "#f0dedd" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#e4c18d" }
title_warn  = { fg = "#ffb3b2" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#ffb3b2" }
active = { fg = "#e4c18d", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb3b2" }
value  = { fg = "#f0dedd" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#ffb3b2", bg = "#561d20" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#ffb3b2" }
title   = {}
hovered = { fg = "#ffdead", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#f0dedd" }
run    = { fg = "#f0dedd" }
footer = { fg = "#442929", bg = "#e6bdbc" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#f0dedd" },
    { url = "*/", fg = "#ffb3b2" },
]

# : ]]]