cursor            #97ccf9
cursor_text_color #003450

foreground            #e0e3e8
background            #101417
selection_foreground  #22323f
selection_background  #b8c8d9
url_color             #d0bfe7

#: black 000000 767676
color0  #8b9198
color8  #8b9198
#: red cc0403 f2201f
color1  #ffb4ab
color9  #ffb4ab
#: green 19cb00 23fd00
color2  #d0bfe7
color10 #d0bfe7
#: yellow cecb00 fffd00
color3  #b8c8d9
color11 #b8c8d9
#: blue 0d73cc 1a8fff
color4  #97ccf9
color12 #97ccf9
#: magenta cb1ed1 fd28ff
color5  #2a638a
color13 #2a638a
#: cyan 0dcdcd 14ffff
color6  #cbe6ff
color14 #cbe6ff
#: white dddddd ffffff
color7  #e0e3e8
color15 #e0e3e8

mark1_foreground #003450
mark1_background #97ccf9
mark2_foreground #22323f
mark2_background #b8c8d9
mark3_foreground #362b4a
mark3_background #d0bfe7