cursor            #ffb3ae
cursor_text_color #571e1c

foreground            #f1dedd
background            #1a1111
selection_foreground  #442927
selection_background  #e7bdb9
url_color             #e2c28c

#: black 000000 767676
color0  #a08c8b
color8  #a08c8b
#: red cc0403 f2201f
color1  #ffb4ab
color9  #ffb4ab
#: green 19cb00 23fd00
color2  #e2c28c
color10 #e2c28c
#: yellow cecb00 fffd00
color3  #e7bdb9
color11 #e7bdb9
#: blue 0d73cc 1a8fff
color4  #ffb3ae
color12 #ffb3ae
#: magenta cb1ed1 fd28ff
color5  #904a46
color13 #904a46
#: cyan 0dcdcd 14ffff
color6  #ffdad7
color14 #ffdad7
#: white dddddd ffffff
color7  #f1dedd
color15 #f1dedd

mark1_foreground #571e1c
mark1_background #ffb3ae
mark2_foreground #442927
mark2_background #e7bdb9
mark3_foreground #402d04
mark3_background #e2c28c