cursor            #a9c7ff
cursor_text_color #08305f

foreground            #e2e2e9
background            #111318
selection_foreground  #283141
selection_background  #bdc7dc
url_color             #dcbce1

#: black 000000 767676
color0  #8e9099
color8  #8e9099
#: red cc0403 f2201f
color1  #ffb4ab
color9  #ffb4ab
#: green 19cb00 23fd00
color2  #dcbce1
color10 #dcbce1
#: yellow cecb00 fffd00
color3  #bdc7dc
color11 #bdc7dc
#: blue 0d73cc 1a8fff
color4  #a9c7ff
color12 #a9c7ff
#: magenta cb1ed1 fd28ff
color5  #405f90
color13 #405f90
#: cyan 0dcdcd 14ffff
color6  #d6e3ff
color14 #d6e3ff
#: white dddddd ffffff
color7  #e2e2e9
color15 #e2e2e9

mark1_foreground #08305f
mark1_background #a9c7ff
mark2_foreground #283141
mark2_background #bdc7dc
mark3_foreground #3e2845
mark3_background #dcbce1