cursor            #cccb76
cursor_text_color #323200

foreground            #e6e3d5
background            #14140c
selection_foreground  #323218
selection_background  #cac8a4
url_color             #a4d0bc

#: black 000000 767676
color0  #939182
color8  #939182
#: red cc0403 f2201f
color1  #ffb4ab
color9  #ffb4ab
#: green 19cb00 23fd00
color2  #a4d0bc
color10 #a4d0bc
#: yellow cecb00 fffd00
color3  #cac8a4
color11 #cac8a4
#: blue 0d73cc 1a8fff
color4  #cccb76
color12 #cccb76
#: magenta cb1ed1 fd28ff
color5  #626118
color13 #626118
#: cyan 0dcdcd 14ffff
color6  #e8e78f
color14 #e8e78f
#: white dddddd ffffff
color7  #e6e3d5
color15 #e6e3d5

mark1_foreground #323200
mark1_background #cccb76
mark2_foreground #323218
mark2_background #cac8a4
mark3_foreground #0b372a
mark3_background #a4d0bc