cursor            #aec6ff
cursor_text_color #122f60

foreground            #e2e2e9
background            #121318
selection_foreground  #293041
selection_background  #bfc6dc
url_color             #dfbbde

#: black 000000 767676
color0  #8e9099
color8  #8e9099
#: red cc0403 f2201f
color1  #ffb4ab
color9  #ffb4ab
#: green 19cb00 23fd00
color2  #dfbbde
color10 #dfbbde
#: yellow cecb00 fffd00
color3  #bfc6dc
color11 #bfc6dc
#: blue 0d73cc 1a8fff
color4  #aec6ff
color12 #aec6ff
#: magenta cb1ed1 fd28ff
color5  #455e91
color13 #455e91
#: cyan 0dcdcd 14ffff
color6  #d8e2ff
color14 #d8e2ff
#: white dddddd ffffff
color7  #e2e2e9
color15 #e2e2e9

mark1_foreground #122f60
mark1_background #aec6ff
mark2_foreground #293041
mark2_background #bfc6dc
mark3_foreground #402843
mark3_background #dfbbde