cursor            #ffb690
cursor_text_color #542202

foreground            #f0dfd8
background            #1a120e
selection_foreground  #432b1e
selection_background  #e6beab
url_color             #cfc890

#: black 000000 767676
color0  #a08d84
color8  #a08d84
#: red cc0403 f2201f
color1  #ffb4ab
color9  #ffb4ab
#: green 19cb00 23fd00
color2  #cfc890
color10 #cfc890
#: yellow cecb00 fffd00
color3  #e6beab
color11 #e6beab
#: blue 0d73cc 1a8fff
color4  #ffb690
color12 #ffb690
#: magenta cb1ed1 fd28ff
color5  #8d4e2a
color13 #8d4e2a
#: cyan 0dcdcd 14ffff
color6  #ffdbca
color14 #ffdbca
#: white dddddd ffffff
color7  #f0dfd8
color15 #f0dfd8

mark1_foreground #542202
mark1_background #ffb690
mark2_foreground #432b1e
mark2_background #e6beab
mark3_foreground #353107
mark3_background #cfc890