# Fonts
font_family        JetBrainsMono Nerd Font
font_size 16
cursor_shape block
shell_integration no-cursor

# Window
window_padding_width 25
hide_window_decorations yes
background_opacity 1
background_blur 50
enable_audio_bell no

# OS window confirmation disable
confirm_os_window_close 0


# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME